### PR TITLE
#101: Fixes invalid call-back for buffers targetted by vkCmdCopyQuery…

### PR DESCRIPTION
**Pull request by DominikWitczakAMD**
…PoolResults()

This addresses #101

### CODE REVIEW

**Comment by lentinem** [comment]
-1. It's still not clear to me that this isn't required. The spec says: "VK_BUFFER_USAGE_TRANSFER_DST_BIT indicates that the buffer can be used as the destination of a transfer command." as well as "vkCmdCopyQueryPoolResults is considered to be a transfer operation" which implies (thought its not explicitly stated) that this should be used.

**Comment by janharaldfredriksen-arm** [comment]
This got to be required - it shouldn't be any different than other copy (or transfer) commands in this respect.

This condition isn't stated in the Valid Usage section for vkCmdCopyQueryPoolResults, but I suspect we just forgot and that we should add "dstBuffer must have been created with VK_BUFFER_USAGE_TRANSFER_DST_BIT usage flag" there.

Do you agree? If so, shall we create a spec bug instead?

**Comment by DominikWitczakAMD** [comment]
Don't mind either way! If that's what your driver needs to work fine, I'm all for getting this requirement added to the valid usage section.

The only reason I put up this MR is that I wanted to pinch someone for a reaction ;) Apparently, it worked!

**Comment by lentinem** [comment]
As probably obvious from my comment I agree with Jan Harald and can propose that change unless you want to do so.

**Comment by DominikWitczakAMD** [comment]
Yes, please, that would be very helpful.

**Comment by lentinem** [comment]
https://gitlab.khronos.org/vulkan/vulkan/merge_requests/1213

**Comment by tobine** [comment]
closing

**Pull request closed without merging**
