### PR TITLE
external: Update commit IDs: glslang, tools, header

### PR DESCRIPTION
**Pull request by mikew-lunarg**
Update to latest commit IDs.

### CODE REVIEW

**Comment by chrisforbes** [comment]
What about android?

**Comment by mikew-lunarg** [comment]
I leave those to Cody, as there is coordination w/ shaderc known-good
<https://github.com/google/shaderc/tree/known-good> that I have no control
over.
-- mew

**Comment by cnorthrop** [comment]
Yes, ideally we would update the Android revisions each time known-good moves forward, but I haven't had time to figure out an automated way to do that.

We'd hoped to get desktop and Android on the same update schedule, but LunarG wants to ship top of tree with each SDK update, so we can't achieve that goal.

**Comment by cnorthrop** [comment]
Thinking about this now, perhaps we should just check in the shaderc known-good json file and train our scripts to pull out the revisions we need.  Then we would still have a running log of what toolchain we're using (for reproducible toolchains while bisecting) with a brute simple way of updating it.  Part of the challenge here is just find the time to manually update and test the new toolchain.  It isn't hard, just tedious and recurring.

**Pull request merged**
