### PR TITLE
layers: Fix Graphics Pipeline pointers not ignored

### PR DESCRIPTION
**Pull request by krOoze**
Some `VkGraphicsPipelineCreateInfo` pointers must be ignored under some conditions,
but were not in the layers (resulting in crashes despite valid use).

### CODE REVIEW

**Comment by mark-lunarg** [comment]
We'd need to get the tests fixed and include those changes with this commit.  @krOoze, do you feel up to that?

**Comment by krOoze** [comment]
@mark-lunarg Yeah, I am in middle of that. I will update you when it is done (or I fail).

**Comment by krOoze** [comment]
@mark-lunarg Tests fixed. Also positive test added.

**Comment by krOoze** [comment]
@tobine I should be able to set up Intel Mesa environment. It may take a while though.

**Comment by krOoze** [comment]
@tobine It should work now.
It is annoying though having to track state in `unique_objects`. Perhaps some replacement would be better for `safe_struct` that just `const_cast`s the original and unwraps the handles in-place for the duration of the call.

**Comment by mark-lunarg** [comment]
@tobine, anything remaining to do on this PR as far as you are concerned?

**Comment by krOoze** [comment]
Rebased, but there's some problem with the clang build here.
The `cmake` fails finding `clang` while building the external `glslang`. So, I would think it is not my fault.

**Comment by mark-lunarg** [comment]
Didn't see any clang issues, fixed up some small clang-format issues and pushed to Master.

**Comment by cnorthrop** [comment]
This is crashing on Intel Mesa, Mali, and IMG still.

**Comment by krOoze** [comment]
@mark-lunarg So I found. I rebased today again and the test passed, so I deleted the message.
@cnorthrop That's a shame, it worked... I will test on Intel MESA again then.

**Comment by cnorthrop** [comment]
I'm on a fairly old Mesa build at this point, it could be that newer builds are okay.  It is crashing in the driver, here's the stack trace we're seeing:

```
2918│ static inline void
2919│ GEN9_3DSTATE_DS_pack(__gen_user_data *data, void * restrict dst,
2920│                      const struct GEN9_3DSTATE_DS * restrict values)
2921│ {
2922│    uint32_t * restrict dw = (uint32_t * restrict) dst;
2923│
2924├>   dw[0] =
2925│       __gen_uint(values->CommandType, 29, 31) |
2926│       __gen_uint(values->CommandSubType, 27, 28) |
2927│       __gen_uint(values->_3DCommandOpcode, 24, 26) |
2928│       __gen_uint(values->_3DCommandSubOpcode, 16, 23) |
2929│       __gen_uint(values->DWordLength, 0, 7);

[0;32m[ RUN      ] [mVkLayerTest.DynamicStencilReadNotBound

Program received signal SIGSEGV, Segmentation fault.
GEN9_3DSTATE_DS_pack (data=data@entry=0x7fffffffc770, dst=0xffffffffffffffff, values=values@entry=0x7fffffffa620) at ../../../src/intel/genxml/gen9_pack.h:2924
(gdb) bt
#0  GEN9_3DSTATE_DS_pack (data=data@entry=0x7fffffffc770, dst=0xffffffffffffffff, values=values@entry=0x7fffffffa620) at ../../../src/intel/genxml/gen9_pack.h:2924
#1  0x00007ffff63a1d4b in blorp_exec (batch=batch@entry=0x7fffffffc770, params=params@entry=0x7fffffffc0f0) at ../../../src/intel/blorp/blorp_genX_exec.h:1338
#2  0x00007ffff63a4b1b in gen9_blorp_exec (batch=0x7fffffffc770, params=0x7fffffffc0f0) at genX_blorp_exec.c:169
#3  0x00007ffff6262ae5 in blorp_clear_depth_stencil (batch=batch@entry=0x7fffffffc770, depth=depth@entry=0x7fffffffc790, stencil=stencil@entry=0x7fffffffc7f0, level=0, start_layer=1, start_layer@entry=0, num_layers=4294967294, num_layers@entry=4294967295, x0=0, y0=0, x1=256, y1=256, clear_depth=true, depth_value=1, stencil_mask=255 '\377', stencil_value=0 '\000') at blorp/blorp_clear.c:371
#4  0x00007ffff60f1373 in anv_CmdClearDepthStencilImage (commandBuffer=<optimized out>, image_h=0x1893f20, imageLayout=<optimized out>, pDepthStencil=0x7fffffffce20, rangeCount=<optimized out>, pRanges=<optimized out>) at anv_blorp.c:858
#5  0x00007ffff45960cf in unique_objects::CmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x1893f20, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/build/layers/unique_objects_wrappers.h:1949
#6  0x00007ffff3d1a2cd in core_validation::CmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x6, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/layers/core_validation.cpp:6235
#7  0x00007ffff379285a in object_tracker::CmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x6, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/build/layers/object_tracker.cpp:2092
#8  0x00007ffff325a092 in parameter_validation::vkCmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x6, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/build/layers/parameter_validation.cpp:4820
#9  0x00007ffff2ebe4a4 in threading::CmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x6, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/build/layers/thread_check.h:2646
#10 0x00007ffff7bb1a2a in vkCmdClearDepthStencilImage (commandBuffer=0x177d360, image=0x6, imageLayout=VK_IMAGE_LAYOUT_GENERAL, pDepthStencil=0x7fffffffce20, rangeCount=1, pRanges=0x7fffffffce50) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/loader/trampoline.c:1787
#11 0x00000000005937df in VkCommandBufferObj::ClearAllBuffers (this=0x180bb40, clear_color=..., depth_clear_color=1, stencil_clear_color=0, depthStencilObj=0x177eb80) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/vkrenderframework.cpp:1328
#12 0x000000000047e01c in VkLayerTest::GenericDrawPreparation (this=0x13c3d10, commandBuffer=0x180bb40, pipelineobj=..., descriptorSet=..., failMask=BsoFailStencilReadMask) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/layer_validation_tests.cpp:607
#13 0x000000000047dbb0 in VkLayerTest::VKTriangleTest (this=0x13c3d10, vertShaderText=0x71f020 <bindStateVertShaderText> "#version 450\nvec2 vertices[3];\nvoid main() {\n      vertices[0] = vec2(-1.0, -1.0);\n      vertices[1] = vec2( 1.0, -1.0);\n      vertices[2] = vec2( 0.0,  1.0);\n   gl_Position = vec4(vertices[gl_VertexI"..., fragShaderText=0x71f120 <bindStateFragShaderText> "#version 450\n\nlayout(location = 0) out vec4 uFragColor;\nvoid main(){\n   uFragColor = vec4(0,1,0,1);\n}\n", failMask=BsoFailStencilReadMask) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/layer_validation_tests.cpp:577
#14 0x00000000004a1289 in VkLayerTest_DynamicStencilReadNotBound_Test::TestBody (this=0x13c3d10) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/layer_validation_tests.cpp:4889
#15 0x00007ffff7727804 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x13c3d10, method=&virtual testing::Test::TestBody(), location=0x7ffff7733dab "the test body") at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2078
#16 0x00007ffff772286b in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x13c3d10, method=&virtual testing::Test::TestBody(), location=0x7ffff7733dab "the test body") at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2114
#17 0x00007ffff7707712 in testing::Test::Run (this=0x13c3d10) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2151
#18 0x00007ffff7707f62 in testing::TestInfo::Run (this=0x13a3cc0) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2326
#19 0x00007ffff77085fb in testing::TestCase::Run (this=0x139f060) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2444
#20 0x00007ffff770f75c in testing::internal::UnitTestImpl::RunAllTests (this=0x139ec60) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:4311
#21 0x00007ffff772875d in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x139ec60, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x7ffff770f48a <testing::internal::UnitTestImpl::RunAllTests()>, location=0x7ffff77345b8 "auxiliary test code (environments or event listeners)") at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2078
#22 0x00007ffff77236e1 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x139ec60, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x7ffff770f48a <testing::internal::UnitTestImpl::RunAllTests()>, location=0x7ffff77345b8 "auxiliary test code (environments or event listeners)") at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:2114
#23 0x00007ffff770e304 in testing::UnitTest::Run (this=0x7ffff794e4e0 <testing::UnitTest::GetInstance()::instance>) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/src/gtest.cc:3922
#24 0x0000000000557bbb in RUN_ALL_TESTS () at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/gtest-1.7.0/include/gtest/gtest.h:2297
#25 0x0000000000550bea in main (argc=1, argv=0x7fffffffdbb8) at /home/buildbot/LVL-buildbot/LVL-ubuntu-slave/LVL_ubuntu/build/tests/layer_validation_tests.cpp:25542
(gdb) 
```

**Comment by cnorthrop** [comment]
The other two devices are also crashing in the driver, different tests though:

> Mali:  VkLayerTest.DynamicStencilReadNotBound
> IMG:  VkPositiveLayerTest.PSOPolygonModeValid

**Comment by tobine** [comment]
@mark-lunarg @krOoze sorry I never responded to your inquiries back in Aug. I just totally missed them.

I've been going through the code and I don't like having the state tracking in PV or unique_objects.

@krOoze what was the original issue that motivated these changes? I definitely see what you're doing and see that we have a bug in validation where we don't correctly ignore those gfx pipeline ptrs in some cases when we should. I'm wondering if a less invasive solution would be a good compromise, at least initially.

My current thought is that we could have core_validation recognize the cases where VkGraphicsPipelineCreateInfo are not NULL and should be ignored, and issue a warning callback noting that validation has a bug in this case and we recommend the app to set the ptrs that should be ignored to NULL. Any other thoughts, ideas?

**Comment by mark-lunarg** [comment]
@tobine, would this be done with no intent to fix the issue permanently in the future?  As much of an outlier as this is (at least in UO, we could just remove the checks in PV) it does fix the problem.

**Comment by krOoze** [comment]
@cnorthrop Ideed it still passes for me on Intel Mesa.
Looks kinda lot like the old crashes. Are you sure you are using updated branch (it is `-f` updated so you probably need to clone it again or `reset --hard origin/fix_ignore_pTessellationState`.
The tests are unrelated and shouldn't really crash (asuming they work on master branch).

@tobine 
The issue is that some pointers in the `VkGraphicsPipelineCreateInfo` are allowed to be invalid by the spec, but were not ignored in the layers. This led to crashes even if the Application was valid.

The color and depth struct depend on non-local state (the presence of a color resp. depth attachment in the renderpass). That creates the need for state tracking.

I was also giving it some thought and the solutions that came to me are:

a) Appeal to the spec makers to change the usage. Considering it didn't work in the layers, there are probably not many such usages in the wild yet.

b) Accept defeat and do the state tracking.

c) Make an exception in the autogenerated layers.
- parameter_validation theoretically needs to check those structs **if** they must be valid (and without tracking it does not know), there's no way around that. But it could be deferred to core_validation
- unique_object does not fundamentally need to touch those two structs (there are no handles in them, unless extended in the future). It really requires tracking because of how `safe_struct`s are generated. It would require some hacking there in the generator script to use the original pointers and then not accidentally delete them. 

d) Remove the checking completely for those two structs and make a "not implemented" warning on each `vkCreateGraphicsPipeline` (would potentially spam log though).

**Comment by tobine** [comment]
Note that in the case of the DynamicStencilReadNotBound test, which is 2/3 crashing cases, with the changes from @krOoze the test now initializes m_depthStencil in VkRenderFramework which causes the attempt to clear it whereas prior to the changes the surface was not initialized so the clear was never attempted. Still not clear to me why the 2 cases crash, though. If latest MESA is passing, then that may be driver bug, which is certainly possible in the IMG case as well.

We could certainly attempt to get the spec changed. I'm not sure that's the right solution but even if it is I'm not too optimistic that it would get approved. It's possible that an older version of the spec required the ptrs to be null.

For the parameter checks I definitely prefer the option to defer them to core_validation time, which already handles many of these state-ful param checks.
Unique_objects is trickier. The hack you @krOoze mentions would work but be ugly. I think I'd find it less ugly than adding the state tracking to unique_objects, though, as that solution also requires custom modifications to safe_struct anyway. So the alternate hack could just pass in a single bool to safe_VkGraphicsPipelineCreateInfo.initialize() function that would trigger the structs of interest to have the original ptrs passed-through. That would also set a bool in the struct so that at destruction the passed-through ptrs are not deleted.

I'd be ok with that as an alternative, thoughts from @chrisforbes ?

**Comment by krOoze** [comment]
> If latest MESA is passing, then that may be driver bug, which is certainly possible in the IMG case as well.

I wouldn't blame drivers just yet. I found at least two more errors in `VKTriangleTest` (the images does not have required usage for `vkCmdClear`, and  `VK_QUEUE_FAMILY_IGNORED` is missing on barrier).

**Comment by mark-lunarg** [comment]
This one is kinda languishing, can we bump it along or abandon it for now?  What needs to happen next?

**Comment by krOoze** [comment]
@mark-lunarg Right. Assumably it still rubs some drivers the wrong way.

I have in the works something that revises `VKTriangleTest` and fixes couple of IMO invalid usages thereing, which could fix it.

I do not have access to any of the platforms affected. Anybody with those could potentially debug or implement workarounds in this faster.

I will at least rebase it, so it can be worked with, and see if testing reveals something new...

**Comment by tobine** [comment]
@krOoze be sure and ping me in a comment when you rebase and I'll resubmit to our internal farm to see where it stands.

**Comment by krOoze** [comment]
@tobine ping.

**Comment by tobine** [comment]
Still has the same 3 device-specific fails that @cnorthrop noted on Sept 12.
I'd like to keep this PR around.
This is valuable as if we can land it it should lead to improvements in our tests and/or point out some vendor issues that we can create CTS tests for.
I'll isolate the cause of each fail and we can address them individually.

**Comment by krOoze** [comment]
@tobine The fixes to `VKTriangleTest` are just a hack to make it work here, and are expanded in #2240 . That's probably what should be testes now.

**Comment by tobine** [comment]
Only remaining issues I see is hitting segF on two systems in PSOPolygonModeValid test. I'll take a look to isolate cause.

**Comment by Tony-LunarG** [comment]
I accounted for the PSOPolygonModeValid failure, but I also see CreateGraphicsPipelineWithIgnoredPointers crashing on NexusPlayer - is it in the same boat?

**Comment by tobine** [comment]
@Tony-LunarG Yes, add CreateGraphicsPipelineWithIgnoredPointers to NexusPlayer exclusion list. I've updated doc to reflect this.

**Pull request merged**
