### PR TITLE
Github 1544: Fix building with MinGW-w64

### PR DESCRIPTION
**Pull request by DragoonX6**
First of all, sorry for the big commit history, I made my changes on an SDK tag and then later merged them onto master.

I've updated googletest to 1.8.0 which further increases compatibility with MinGW-w64, however only master builds out of the box without disabling pthreads.

I also had to add some changes to the CMakeLists to make it build in parallel with MSVC2017 using ninja and to work around a bug where it thinks `_strdup` is deprecated (which is normally meant to fire on the use of strdup).
The rest of the changes are all targeted at MinGW-w64.

Here's a diffstat without the googletest replacement to make it a little easier to navigate:
```
demos/vulkaninfo.c                |  2 +-
 include/vulkan/vk_platform.h      |  5 +++++
 include/vulkan/vk_sdk_platform.h  | 17 +++++++++++++++++
 libs/vkjson/CMakeLists.txt        |  1 +
 loader/CMakeLists.txt             |  6 +++++-
 loader/loader.rc                  |  4 ++++
 loader/vk_loader_platform.h       |  9 ++++++---
 tests/CMakeLists.txt              | 10 ++++++++--
 tests/loader_validation_tests.cpp |  1 +
 tests/test_common.h               |  9 +++++++--
 tests/vktestframework.h           |  1 +
 11 files changed, 56 insertions(+), 9 deletions(-)
```

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@DragoonX6, can you please rebase the changes onto latest master and repush the branch?  Also, please reformat the commit messages to follow the repo pattern, starting with 'build: " or "loader: ".  Then we'll get this assigned -- Thanks!

**Comment by mark-lunarg** [comment]
Hey, it also looks like there are changes to `vk_platform.h `included in this patch series.  This file comes from Khronos through the Vulkan-Docs repo and any changes would have to be made there.

**Comment by mark-lunarg** [comment]
@DragoonX6, bump.

**Comment by DragoonX6** [comment]
Sorry, I've been meaning to get to this. I'll try to get on it this weekend.

**Comment by DragoonX6** [comment]
Sorry it's months later, I'm actually working on it now.
It's less work for me to redo the work than work out the conflicts that this causes, because I've not worked on it for so long.
I'll be back with a new PR later, which will be based on master.

**Pull request closed without merging**
