### PR TITLE
GH #1444 add wayland include dir to CMakeLists.txt

### PR DESCRIPTION
**Pull request by heijligen**
On some Linux distributions (e.g  openSUSE, Fedora) the wayland headers are in
a subdirectory.
Adding WAYLAND_CLIENT_INCLUDE_DIR to include_directories in CMakeLists.txt
will fix this issue.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@heijligen, at first glance this looks good.  To make merging easier, can you fix your commit message to match what's listed in the contributing doc (and to match the other project commits)?  And, it looks like the  new 'include' line needs to be aligned correctly.  You can force push your changed commit to the same branch...

**Comment by mark-lunarg** [comment]
@heijligen, Sweet!  Thank you very much.  We're running this through some testing here...

**Comment by heijligen** [comment]
I'm running openSUSE. there it is /usr/include/wayland/. I've found a package with the same file structure on fedoras build system.

**Comment by johnzupin** [comment]
@heijligen Ok thanks for the update and pull-request!

**Pull request merged**
