### PR TITLE
Pull in gtest as a submodule

### PR DESCRIPTION
**Pull request by mark-lunarg**
LVL has been carting around a snapshot of gtest that was grabbed in 2014.  Changed build to pull in this source code as a submodule.

Added the submodule update as a step in the **update_external_sources** scripts, but it may still bite you if this step is skipped -- you can instead run  

**git submodule update --init --recursive**

@karl-lunarg, please check this for MacOS.

### CODE REVIEW

**Comment by karl-lunarg** [comment]
This branch builds OK on macOS.

There are a bunch of unused function messages, for example:
```
In file included from /Users/karl/src/Vulkan-LoaderAndValidationLayers/layers/vk_layer_utils.cpp:28:
In file included from /Users/karl/src/Vulkan-LoaderAndValidationLayers/layers/vk_layer_utils.h:26:
/Users/karl/src/Vulkan-LoaderAndValidationLayers/layers/vk_layer_logging.h:679:17: warning: 
      unused function 'layer_copy_tmp_debug_messengers' [-Wunused-function]
static VkResult layer_copy_tmp_debug_messengers(const void *pChain, uint...
```

I don't know if these were introduced by this PR or not.

**Comment by karl-lunarg** [comment]
I'll have to address the warnings I mentioned above, and some others, in a different commit/PR.

After fixing the minor clang-format complaint, this looks ok.

**Comment by mark-lunarg** [comment]
@karl-lunarg, those warnings are from Mark's DebugUtils extension stuff, and he has a PR in-flight for them. https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2505

**Comment by mark-lunarg** [comment]
Fixed C-F issue and pushed to Master.

**Pull request closed without merging**
