### PR TITLE
Swapchain merge part1

### PR DESCRIPTION
**Pull request by chrisforbes**
This moves some of the low-hanging fruit from swapchain to core validation, one check at a time. These first few checks are what CV is most interested in, as they open the door to general complaining about operations on images which are not currently acquired by the app.

[After several more series like this, there will be just the empty husk of the old layer remaining, and at that point I'll delete it.]

### CODE REVIEW

**Comment by chrisforbes** [comment]
Right, I can tweak the enums as a first step.

**Comment by chrisforbes** [comment]
Rebased and enums tweaked.

**Comment by mark-lunarg** [comment]
:+1:

**Comment by chrisforbes** [comment]
Pushed to master on the basis of @mark-lunarg's review.

**Comment by ianelliottus** [comment]
LGTM.  Sorry to be late.

**Pull request closed without merging**
