### PR TITLE
layers: Fix bug in cmd buffer framebuffer binding

### PR DESCRIPTION
**Pull request by tobine**
If cmd buffers were freed via DestroyCommandPool, then the framebuffer links to the
individual cb_nodes were not getting cleared. Fix that issue.

This is initial, simple solution to avoid crash, need smarter solution long-term.

### CODE REVIEW

**Comment by lentinem** [comment]
Please add a test that exposes the issue.

**Comment by tobine** [comment]
Test added that exposes the issue.

**Comment by lentinem** [comment]
+1

**Comment by tobine** [comment]
cherry-picked and pushed to master

**Pull request closed without merging**
