### PR TITLE
tests: Modify ErrorMonitor for warn behavior

### PR DESCRIPTION
**Pull request by mark-lunarg**
For Positive tests, warnings and perf-warnings should not cause the test to fail.  This change makes the default ERROR only, and allows an individual LVT to specify exactly which flags are to be checked.

Using ExpectSuccess() is now configurable for custom combinations
of debug flags.

Change-Id: Ic0917cfa46fc15207d265d392020aadf2f66b675

### CODE REVIEW

**Comment by tobine** [comment]
LGTM :+1:
cherry-picked and pushed to master

**Comment by chrisforbes** [comment]
I can see that you'd want the ability to customize the level, but I'm not really thrilled about the default being relaxed.

The existing positive tests were careful to be clean at all levels. The existing /negative/ tests have piles of problems where they sweep both warnings and unexpected errors under the rug.

What motivates this change?

**Comment by mark-lunarg** [comment]
It is allowable to have warnings or performance warnings and having them
does not necessarily mean the tests are not running cleanly.  The positive
tests run without them currently but this is not a requirement. If folks
feel strongly about it, I can go through and change the current
ExpectSuccess calls to explicitly take warning/perf-warning as additional
args.

**Comment by tobine** [comment]
I don't feel too strongly about it. I recommended ERROR only as the default because we advertise to users that WARN and PERF_WARN are allowed, but something to be aware of. If we make the default stricter that will catch any unexpected warnings that could then be handled as appropriate or the test could just be updated to explicitly set ERROR only if author knew that warnings were acceptable for that test.

**Pull request closed without merging**
