### PR TITLE
layers: Be careful about casts. ptr -> uint64_t& isnt right on 32bit.

### PR DESCRIPTION
**Pull request by chrisforbes**
Unbreaks the 32bit world. Sorry for the noise.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
std::ispointer -- my thing for today.  LGTM!

**Comment by chrisforbes** [comment]
Pushed to master.

**Comment by chrisforbes** [comment]
@mark-lunarg maybe we should use this to do good helpers to get rid of all the reinterpret_cast noise in the other layers?

**Comment by mark-lunarg** [comment]
Yeah, that sounds great!  Maybe put the templates in layer utils or something.  Any ideas for the ultra-noisy log_msg calls?  Blick.

**Pull request closed without merging**
