### PR TITLE
Fix comments of result constants.

### PR DESCRIPTION
**Pull request by diaphore**
`VK_ERROR_INITIALIZATION_FAILED` and `VK_ERROR_DEVICE_LOST` comments are inverted.

### CODE REVIEW

**Comment by lentinem** [comment]
+1

**Comment by dustin-lunarg** [comment]
If you haven't already, you should also submit a pull request against the [vk.xml](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml) file from the [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/) repo.  Vulkan-Docs is the source of this file.  Vulkan-LoaderAndValidationLayers contains a copy of the vk.xml file from Vulkan-Docs, which is used for generating some of the validation code.

**Comment by diaphore** [comment]
@dustin-lunarg Done.

https://github.com/KhronosGroup/Vulkan-Docs/pull/144

**Comment by karl-lunarg** [comment]
Closing since issue moved to Vulkan-Docs.  We'll pick up this change when we next update from Vulkan-Docs.

**Pull request closed without merging**
