### PR TITLE
Update to V1.0.31 header

### PR DESCRIPTION
**Pull request by mark-lunarg**
Wish they were all like this.

### CODE REVIEW

**Comment by courtney-g** [comment]
Starting to make me wonder about how to simplify such updates.
:+1:

**Comment by mark-lunarg** [comment]
Pushed to Master.

**Comment by karl-lunarg** [comment]
@courtney-g   Stop updating the spec as often? :-)

**Comment by TobiasHector** [comment]
@karl-lunarg I previously suggested we didn't need to update the header and xml along with the spec if the only changes were in the spec text, which would remove the need to do this kind of mostly pointless update to the validation layers... At the time nobody thought it would be an issue, but if it's something that's causing you needless busy work, I suggest you raise an issue against the spec :).

**Comment by karl-lunarg** [comment]
Hi @TobiasHector ,  Versions 30 and 31 didn't update the xml or headers, so we could have skipped these.  We've done that before.  But we will pick up the latest, even when there are no changes, just before we release an SDK in order to get the latest in the SDK.  30 was a good example of that.

I think that it is probably globally better if the version of the public header matches the version of the public spec in order to avoid questions about that, if nothing else.  I know that it causes some unneeded version churn of the xml/header file, but we can always pass on pulling in a version that had no changes.

@courtney-g may been suggesting to make the changes simpler.  It could be done in one commit, for example, and probably should be so we don't have version inconsistency across commits.  @mark-lunarg: can we do that in the future?   There are probably ways to automate making the changes to make things easier on us, and we can do that in places where it makes sense.

Also, in the past, we haven't always done pull requests for updates of the version, especially when the changes were only in the version.   I think that pull requests for version updates that add significant features may be valuable so that others can see the additions and what code has been done to cope with the new features.  But perhaps we can refrain from doing pull requests when only the version is different.

**Comment by mark-lunarg** [comment]
Just a side note -- LoaderAndValidationLayers now has dependencies on components outside of the header and xml files.  It's probably a good idea to pick up revisions that modify any valid usage text (which did occur in 30 and 31).  We also check for changes in the python worker-scripts that used for codegen in LVL.  If none of these guys change then sure, it's a no-op.

**Comment by courtney-g** [comment]
@karl-lunarg I was thinking automation. Having to remember to change 16 json files is annoying.

**Pull request closed without merging**
