### PR TITLE
layers: Update subrange checks+tests to new VUIDs

### PR DESCRIPTION
**Pull request by krOoze**
- i.e. disambiguate extension VUIDs from similar VUID in core
 - remove TODO and mark as "None" in db instead
 - simplify function to take only info needed instead of whole ImageViewCreateInfo

### CODE REVIEW

**Comment by krOoze** [comment]
Build failure is master branch commit 2aa3d0a6fd6592fd54bbcf6aa1d064a2b8b758d3 fault. #1822 should fix that.

**Comment by krOoze** [comment]
@mark-lunarg It's almost two weeks. Can I has reviews + merge? 😿

**Comment by daveh-lunarg** [comment]
@krOoze, I'm looking at this PR, will review by tomorrow.

**Comment by daveh-lunarg** [comment]
Looks good, runs through our CI without problem.  Pushing.

**Comment by daveh-lunarg** [comment]
Thanks, @krOoze!

**Pull request merged**
