### PR TITLE
Windows shared memory support for layers

### PR DESCRIPTION
**Pull request by mark-lunarg**
Adding Windows shared memory support to the layers.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@cnorthrop , can you please give this a run through the test farm?

**Comment by stroyan** [comment]
What is the intended use of this shared memory?  Validation layers haven't ventured into inter-process communication before.  You will need an IPC mutex such as windows' CreateMutex or a pthread mutex set to PTHREAD_PROCESS_SHARED to protect references to shared memory such as `shared_data->reference_count++;`

**Comment by cnorthrop** [comment]
We're getting some Android failures, sync'd with Mark offline.

**Comment by mark-lunarg** [comment]
@stroyan -- Since this is not intended for cross-process sharing, do you still suggest that more robust protection is needed for this change?

**Comment by stroyan** [comment]
While this is not intended for cross-process sharing, I don't see anything that will prevent different processes from sharing this memory.  You may need to use a unique name parameter to CreateFileMapping to avoid collisions.  You could concatenate the value of _getpid().

**Comment by mark-lunarg** [comment]
Shelving this for now.

**Pull request closed without merging**
