### PR TITLE
tests: Update MismatchedQueueFamiliesOnSubmit

### PR DESCRIPTION
**Pull request by krOoze**
- report clearly if it is skipped
- don't rely on test state for the pool
- use VUID and update database
- should fix one of the "Unexpected" in CI tests

### CODE REVIEW

**Comment by krOoze** [comment]
Actually, abort. There seem to stil be bug on `vkGetDeviceQueue`. The queue family is probably not included in `VkDeviceQueueCreateInfo`.

**Comment by tobine** [comment]
@krOoze , I missed your comment and merged so I went ahead and reverted for now.

**Comment by krOoze** [comment]
@tobine Ah, I see what the problem is. The `powervr_rogue_ge8300` exposes one of those 0 `queueCount` families... apparently that is a valid thing to do.

Fix soon. Should I make a new PR for it?

**Comment by tobine** [comment]
@krOoze Yes, just open new PR

**Pull request merged**
