### PR TITLE
More fence tracking fixes

### PR DESCRIPTION
**Pull request by chrisforbes**
This series unhacks various weird things in fence handling.

### CODE REVIEW

**Comment by chrisforbes** [comment]
@mark-lunarg any chance this can make it in before your 1.17 code freeze? The fence behavior is currently pretty broken in master.

**Comment by mark-lunarg** [comment]
Yeah, I'd love to get it in -- I have promised it to several folks on LunarXchange.  I was waiting for Tobin or Michael to take a look, but I'll run it through our build server and push it (if no problems or outside objections).  Has it already been through y'all's test-farm deal?

**Comment by tobine** [comment]
I checked this out today and ran it on android and LGTM 👍

**Comment by mark-lunarg** [comment]
Great!  Vetting it here and I'll push it shortly.

**Comment by mark-lunarg** [comment]
Cherry-picked and pushed to Master.  

c8592f1 layers: Get rid of fence->swapchain link
6c87c6a layers: Untangle validate+update in QueuePresentKHR
f91af4d layers: Fix AcquireNextImageKHR handling of sync objects
5e92f3c layers: Add getSemaphoreNode helper
cdb1ea0 layers: Rework fence state tracking
d591291 tests: Add a test for broken CREATE_SIGNALED handling
6e9b1f8 tests: Exercise unbounded stack use in decrementResources
df1846b layers: Tidy decrementResources a bit
accf816 layers: use getFenceNode in decrementResources
49f6132 layers: Pass layer_data to verifyWaitFenceState
9b48b44 layers: use getFenceNode in verifyWaitFenceState
c759853 layers: Fix InvalidMemoryMapping not setting structure type
02fdfb7 layers: Remove some MT leftovers

**Comment by chrisforbes** [comment]
Thanks @mark-lunarg, there will be at least one more batch of changes to follow for next release, but this deals with the worst of it.

**Pull request closed without merging**
