### PR TITLE
external: Update commit IDs: glslang,tools,header

### PR DESCRIPTION
**Pull request by mikew-lunarg**
Update external reference commit IDs for Desktop and Android.

An this time, this PR is not immediately intended for merge, but rather as a heads-up of the commits to consider, for testing purposes.  Depending on testing (and feedback to the upstream repos), these commits may be revised.

I've included the Android externals in this as well.  Let me know if that is desirable.

### CODE REVIEW

**Comment by cnorthrop** [comment]
Updating Android is desirable if the revisions are coming from [shaderc known-good branch](https://github.com/google/shaderc/tree/known-good).  From the failure I'm guessing they didn't?  I haven't looked at the details.

**Comment by mikew-lunarg** [comment]
No, these 3 externals have been updated from the ToT of the upstreams, not from shaderc

**Comment by mikew-lunarg** [comment]
shaderc was updated this morn to upstreams' top-of-tree at commit d6544c3db582a4ef7c93c3b075c4120409a2feaa
Using that to update LVL.

**Comment by cnorthrop** [comment]
Thanks!

**Pull request merged**
