### PR TITLE
layers: GH337 Track fence from vkQueueBindSparse

### LINKED ISSUE #337: vkQueueBindSparse used with a fence reports a false warning
I'm binding a sparse resource like this (pseudocode):

```
VkFence fence;
vkCreateFence(device, &fenceCreateInfo, NULL, &fence)
vkQueueBindSparse(queue, 1, &bindSparseInfo, fence)
vkWaitForFences(device, 1, &fence, VK_TRUE, ~(0ull));
```

and it results in the following message:

> MEM(WARN): object: 0x61ffe50 type: 7 location: 5346 msgCode: 14: vkWaitForFences called for fence 0x61ffe50 which has not been submitted on a Queue or during acquire next image.

I think the message is incorrect. The fence is properly signaled, because if I omit it from the sparse bind call, `vkWaitForFences` blocks until the timeout is hit.

### PR DESCRIPTION
**Pull request by tobine**
Correctly update fence tracking for vkQueueBindSparse() call.

Michael - I believe this fixes #337, are there any other updates that are needed for fence tracking in vkQueueBindSparse()?

### CODE REVIEW

**Comment by lentinem** [comment]
+1

**Comment by tobine** [comment]
cherry-picked and pushed to master

**Comment by mark-lunarg** [comment]
Tobin this broke the windows build -- reinterpret_cast<uint64_t>blah should be reinterpret_cast< uint64_t &>blah.  I pushed the fix already.

**Comment by tobine** [comment]
Yes, totally my oversight, sorry. I copied the code from vkQueueSubmit() and updated the c-style casts but forgot the ref for windows build.

**Pull request closed without merging**
