### PR TITLE
layers: GH401 -- Separate out stencil store/loadOps

### PR DESCRIPTION
**Pull request by mark-lunarg**
Tobin, can you look to see if you think this would be sufficient for GH401?  I don't have a repro case and was unsure if it needs some special-casing of the attachment types.  Can you take a quick peek?  The guideline-related stuff I have lined up -- right now I'm just wondering about the validity.  Thanks!

### CODE REVIEW

**Comment by tobine** [comment]
I believe this is better than what is currently in place and may functionally address #401. However, I think this change highlights another hole in the code that I'm not certain about. From spec section 7.1 Render Pass Creation note `If the format has depth and/or stencil components, loadOp and storeOp apply only to the depth data, while stencilLoadOp and stencilStoreOp define how the stencil data is handled.`

For the code in question, a depth-stencil format with loadOp of CLEAR and stencilLoadOp of DONT_CARE will queue a function call to set the memory valid due to the single CLEAR loadOp, but no record will be kept of the fact that stencil data is invalid.

So in general it seems that we may need to update the code in question, as well as memory validity tracking, for depth-stencil formats. That doesn't have to be done now, but if others are in agreement we should at least create an issue to track this hole until it can be properly addressed.

**Comment by mark-lunarg** [comment]
OK, then we might as well use this issue to track the necessary changes.

**Comment by karl-lunarg** [comment]
LGTM +1  Are you going to keep this issue to track the memory validity tracking as Tobin mentioned and IAW with the TODO in the new code?

**Comment by mark-lunarg** [comment]
Cherry-picked to Master.  

commit 1a65650f856376768d7b03ea2d080aaff87cacfd
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Fri Jun 10 15:28:17 2016 -0600

    layers: GH401, Break out stencil load/storeOp check

    Stencil attachment load/storeOp settings were being ignored. Added
    format appropriate checks for these flags.

    Change-Id: I6a917fc8a28cbb0d0441152e8d6630defb1b81e3

**Pull request closed without merging**
