### PR TITLE
Swapchain merge part 2, and some OT cleanup and fixes

### PR DESCRIPTION
**Pull request by chrisforbes**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Nice!  Added much functionality and deleted much code at the same time.  👍

**Comment by chrisforbes** [comment]
This is going to involve some tweaks to your current OT changes

**Comment by mark-lunarg** [comment]
@chrisforbes , yeah, I'll redo them right after you push.

**Comment by tobine** [comment]
Change looks good. Test?

**Comment by chrisforbes** [comment]
@tobine Yeah, I got lazy with the tests when moving this stuff. Will fix on monday.

**Comment by chrisforbes** [comment]
tests in follow-up series.

**Comment by chrisforbes** [comment]
Pushed to master.

**Pull request closed without merging**
