### PR TITLE
cube: Add direct to display support

### PR DESCRIPTION
**Pull request by ardaLunarG**
Although this extension is platform agnostic, this commit only enables
it on Linux because this is the only platform I am able to test.

Direct to display is enabled by passing '-DDEMOS_WSI_SELECTION=DISPLAY'
to cmake.

Change-Id: I5f23019d4b0c87104e1f834d3a6901850bfda7a3

### CODE REVIEW

**Comment by ardaLunarG** [comment]
pushed to master

**Comment by Tony-LunarG** [comment]
I was unable to try this in a timely manner for this pull request, but now that I can, I'm getting an INITIALIZATION_FAILED error when cube tries to create a swapchain.  The display code creates a surface and everything goes without errors until swapchain creation.  This is on Ubuntu 16.04, GTX 660ti, driver 375.27.08 which advertises VK_KHR_display support.  Would you expect cube to run with display WSI in this configuration?

**Comment by damienleone** [comment]
Was X running?

**Comment by Tony-LunarG** [comment]
Yes, I had an X server running.

**Comment by damienleone** [comment]
Direct to display is not supposed to work while X is running, since in that
case it's X that owns the display.

On Feb 6, 2017 15:41, "Tony-LunarG" <notifications@github.com> wrote:

Yes, I had an X server running.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1430#issuecomment-277806627>,
or mute the thread

**Comment by damienleone** [comment]
Tony, did you manage to get it to work?

**Comment by Tony-LunarG** [comment]
Yes, I got it working - thanks

**Pull request closed without merging**
