### PR TITLE
layers: Fix typos in ValidateUpdateDescriptorSets

### PR DESCRIPTION
**Pull request by kennyalive**

### CODE REVIEW

**Comment by karl-lunarg** [comment]
Looks like you'll need to make the same sort of change to `tests/layer_validation_tests.cpp`.  Let us know here if you'd like someone else to do that.

**Comment by kennyalive** [comment]
Hello, Karl. I've updated the tests. Thanks.

**Comment by karl-lunarg** [comment]
Thanks!  It would be great if you could squash the commits into one and change the commit message to add "layers: " to the front of the message.  (See CONTRIBUTING.md in this repo.)  It should then be good to go.

**Comment by kennyalive** [comment]
Done.

**Pull request merged**
