### PR TITLE
Fix for ValidateCmdBufImageLayouts

### PR DESCRIPTION
**Pull request by FslNopper**
Filter out the transition from old layouts VK_IMAGE_LAYOUT_UNDEFINED or VK_IMAGE_LAYOUT_PREINITIALIZED

This case only happens, when the above layouts are "left". Can not happen later,
as a transition back to these layouts is forbidden and is checked at another place.

### CODE REVIEW

**Comment by lentinem** [comment]
-1. Please explain why you think this is valid. If the image is in an undefined or preinitialized layout it must be transitioned in some form before use.

**Comment by McNopper** [comment]
Agree, an image has to be transitioned before use and this can be done with either vkCmdWaitEvents or vkCmdPipelineBarrier, having one or more VkImageMemoryBarrier.
Problem is, that ValidateCmdBufImageLayouts is reporting wrong e.g. when vkCmdPipelineBarrier is called doing a first transition. The validation is complaining about current and expected layout but actually this function is doing the transition between old and new layout.

**Comment by McNopper** [comment]
So from my side still +1

**Comment by McNopper** [comment]
The ValidateCmdBufImageLayouts function is so far okay checking other commands, but for the command, actually changing the layout, an exception is needed.

The fix does this.

**Comment by McNopper** [comment]
But I am currently thinking about the use case, when the image has not been transitioned and the image is used by another function. Let me revist the code.

**Comment by lentinem** [comment]
Can you send a repro? It sounds like this is a bug somewhere but I don't think the correct solution is to exempt UNDEFINED and PREINITIALIZED. I'm not sure what this has to do with it currently changing the layout as that would apply regardless of format.

**Comment by McNopper** [comment]
I'll try to find the bug and agree, this does not solve it.

**Comment by McNopper** [comment]
Grrr ... wrong number of level count in subresource range. My code was buggy, validation is correct.

**Pull request closed without merging**
