### PR TITLE
Added loader support for KHR_swapchain and KHR_display_swapchain.

### PR DESCRIPTION
**Pull request by pbantolas**
The loader now discovers if the swapchain or the display_swapchain
extensions are enabled on vkCreateInstance.

Created missing terminator functions for the swapchain extension.

Created missing loader support for the display_swapchain extension by
handling the vkCreateSharedSwapchainsKHR entry point.

### CODE REVIEW

**Comment by pbantolas** [comment]
@jon-lunarg Is this what you had in mind?

**Comment by jon-lunarg** [comment]
Petros:

Thanks for the PR.  Actually the KHR_swapchain and KHR_display_swapchain are device extensions rather than instance extensions so they are treated differently. There is some subtlties that would be probably as hard to describe as just doing the code.  If you want to forge ahead that is fine, I can try to describe some of the issues. But maybe it is better if someone that is more familiar with the loader code just adds support for KHR_display_swapchain extension.

**Comment by pbantolas** [comment]
Jon, agreed, it will be better if someone with more experience did the device extensions. We are mainly interested in support for KHR_display functionality.

**Comment by jon-lunarg** [comment]
okay thanks, closing this

**Pull request closed without merging**
