### PR TITLE
#215: Removes an invalid check in vkCmdBindDescriptorSets()

### PR DESCRIPTION
**Pull request by DominikWitczakAMD**

### CODE REVIEW

**Comment by tobine** [comment]
The comment on that check is a quote from spec section 13.2.5 Descriptor Set Binding:

    dynamicOffsetCount must equal the total number of dynamic descriptors in the sets being bound.

It's the last sentence of the 5th paragraph.
Therefore the check itself should be valid. If you think there's an error in how the check is being executed, that's a separate issue, so please provide details in new issue if that's the case.

**Comment by DominikWitczakAMD** [comment]
That check *is* valid, however its current location is not. If you look closely in the diff, you'll notice the same check outside the loop has been left intact.

It doesn't make any sense to compare the number of dynamic descriptors defined for set N with the total number of dynamic descriptors passed by the user, if the user had specified more than one descriptor set.

**Comment by tobine** [comment]
Thanks, Dominik, you're right. All I saw in diff was killed check so a comment in the PR would have helped.

I missed this repeated code when I was fixing a rebase conflict.
There is similar repeated code in the same place for storing dynamicOffsets. I'll clean that up as well.

**Comment by DominikWitczakAMD** [comment]
Sounds good. Thanks, Michael!

**Comment by tobine** [comment]
merged to master and created #217 to remove similar duplicate code related to dynamicOffsets

**Pull request closed without merging**
