### PR TITLE
Allow input attachment usage in CreateImageView

### PR DESCRIPTION
**Pull request by Tony-LunarG**
Change-Id: Ic0bea63b6ec898e496ba124b57ad8b848bdd0b7d

### CODE REVIEW

**Comment by tobine** [comment]
LGTM :+1:

**Comment by Tony-LunarG** [comment]
Pushed to master.

**Comment by chrisforbes** [comment]
Needs a test?

**Comment by Tony-LunarG** [comment]
Test is in PR #902

**Pull request closed without merging**
