### PR TITLE
layers: Use tmp callback for msgs during vk{Create|Destroy}Instance().

### PR DESCRIPTION
**Pull request by ianelliottus**
This is implements some relatively-new functionality of the VK_EXT_debug_report
extension.  An application can pass VkDebugReportCallbackCreateInfoEXT structs
on the pNext chain given to vkCreateInstance(), in order to setup one or more
callbacks that can be used during vk{Create|Destroy}Instance().  These special,
"temporary callbacks" allow messages (e.g. errors) to be logged during the time
when the debug_report extension is normally not setup.

A set of utilities copy VkDebugReportCallbackCreateInfoEXT structs from the
pNext chain given to vkCreateInstance().  These utilities are used by the
validation layers that may have messages (e.g. errors) during
vk{Create|Destroy}Instance().

### CODE REVIEW

**Comment by tobine** [comment]
Did you run "clang-format --style=file" on these changes? There's a couple of super-wide rows.

**Comment by tobine** [comment]
LGTM :+1:
recommend running changes through clang-format if not already done

**Comment by ianelliottus** [comment]
Okay, I ran "git clang-format", and force-pushed the new commit.

**Comment by mark-lunarg** [comment]
Much better, +1

**Comment by ianelliottus** [comment]
I cherry-picked and pushed the change.

**Pull request closed without merging**
