### PR TITLE
WIP: Remove duplicate count decrement.

### PR DESCRIPTION
**Pull request by lentinem**

### CODE REVIEW

**Comment by tobine** [comment]
LGTM :+1:

**Comment by tobine** [comment]
Tested this out and all 3 demos now flag "DS: Cannot delete semaphore <addr> which is in use."

Switching to :-1: until errors are fixed.

**Comment by lentinem** [comment]
Yea I found that. It's more complicated than this so I labeled it WIP. Will remove if I think I have something but it might take a bit.

**Comment by mark-lunarg** [comment]
Michael is right -- this is the correct thing to do but only part of it, and it'll be part of MR301 when I get it reworked.  Most of the problems fixed at this point (the right way) except for one cross-queue case.

**Comment by mark-lunarg** [comment]
See pull request #309.

**Pull request closed without merging**
