### PR TITLE
windows: Return exit status from test script

### PR DESCRIPTION
**Pull request by cnorthrop**
This is needed for automated testing.

### CODE REVIEW

**Comment by Tony-LunarG** [comment]
The script runs fine, but I am seeing a test that appears new since my last SDK testing, WaitEventThenSet, crashes my Nvidia driver / Windows system.  Is anyone else seeing this?

**Comment by cnorthrop** [comment]
WaitEventThenSet is passing for me on Skylake, but only because it bails early.  I added a printf:
  "EXITING WaitEventThenSet due to queue_props[0].queueCount < 2"

We should consider instrumenting all the bailouts to get more accurate coverage analysis.

We do fail CreatePipelineTessPerVertex on Skylake, but I've snuffed that test until we have time to debug it.

**Comment by cnorthrop** [comment]
I don't think we should hold up this series to understand existing test failures.  The last commit adds the ability to disable tests.  Once this is in, we can start testing Windows builds on our side.

**Comment by dustin-lunarg** [comment]
GitHub is warning that there is no newline at the end of the file.

**Comment by Tony-LunarG** [comment]
I agree that this series is fine and sorry to derail with the test failure

**Comment by cnorthrop** [comment]
Newline added - thanks!  I'll merge it and this will be the basis for precommit validation against master.

**Comment by cnorthrop** [comment]
cherry-picked to master

**Pull request closed without merging**
