### PR TITLE
layers: Make generators Python 2.7-compatible.

### PR DESCRIPTION
**Pull request by null77**
ANGLE and Chromium are fixed with Python 2.7, so we need to update
the generator to something that is compatible with 2.7 and 3.2.
The unicode handling is different between the two, so:

* use io.open to allow specifying encoding with open
* use unicode literals in a few places (u'txt' instead of 'txt')

Change-Id: I1570a45e302a09bb1f99eabc84f50b2ec599944d

PTAL.. necessary for ANGLE to use the Vulkan layers at all.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@null77, generator.py is pulled in directly from the Khronos github:Vulkan-Docs repository upon each header update so any changes for that file will need originate in Khronos gitlab:vulkan/vulkan or Khronos github:Vulkan-Docs.  We'll take a look at the changes for the other files and add them if they don't cause any issues.

**Comment by null77** [comment]
Doh.. OK thanks. I guess I'll have to figure out how to contribute to the gitlab.

**Comment by null77** [comment]
OK my changes have landed against the internal repo. How often do you roll in the changes into this repo?

**Comment by mark-lunarg** [comment]
Looks like the changes made the 1.0.38 header update, so they should be pulled in probably tomorrow sometime.

**Comment by null77** [comment]
Excellent, thank you!

**Comment by mark-lunarg** [comment]
This PR is superseded by #1287.  Closing.

**Comment by null77** [comment]
Mark, did the changes to the non-official builder python files make it in? Namely, the ones for parameter validation, threading, and unique objects?

**Comment by mark-lunarg** [comment]
@null77, no, forgot all about them!  thanks for the reminder.  I'll pull the in as appropriate.  Sorry!

**Comment by null77** [comment]
Thanks, looks like this made it in. Appreciate it.

**Comment by mark-lunarg** [comment]
Pushed to Master.

**Pull request closed without merging**
