### PR TITLE
tests: Fail on unexpected errors

### PR DESCRIPTION
**Pull request by jeremy-lunarg**
Unexpected errors will now cause a test to fail. Explicitly calling
out unexpected errors in the test will still work, but should be used
reluctantly.

Change-Id: I5d121dc453c4acf497643bf10ad02459d0d96f15

### CODE REVIEW

**Comment by mark-lunarg** [comment]
CI hates your patch -- might wanna do a quick check using clang.

**Comment by mark-lunarg** [comment]
Travis CI failures unrelated to change.  Good to Go.

**Comment by cnorthrop** [comment]
This is causing all kinds of test failures on our end.  We are short staffed this week due to Spring Break.  It will be next week before we can look at all of these.  Getting a green light from our larger test pool would have been good before moving forward with this.

**Comment by jeremy-lunarg** [comment]
I brought this patch up yesterday in the F2F. Nobody said anything. What do you want me to do?

**Comment by cnorthrop** [comment]
http://giphy.com/gifs/PFwKHjOcIoVUc

I guess leave it as is and we'll dig out next week.  I don't think we'll have anything to contribute until then anyway.  Thanks Jeremy.

**Comment by jeremy-lunarg** [comment]
Reverting this for now. Sorry for the headache.

**Comment by cnorthrop** [comment]
Thanks, Jeremy.  We'll add SetUnexpectedError to the new cases so you can re-enable this soon.

**Pull request merged**
