### PR TITLE
LVTs: Create new VkPositiveLayerTest class

### PR DESCRIPTION
**Pull request by mark-lunarg**
Created new test class (VkPositiveLayerTest) for positive tests,
moved existing positive test into this class and split tests having
a mix of positive and negative tests. This should make things a bit
cleaner when adding valid usage IDs and adding test names into the
VU database.  In the future the class can be extended to do error
checking automatically.

### CODE REVIEW

**Comment by tobine** [comment]
Running this on our farm as lots of code was touched

**Comment by tobine** [comment]
We're going to have to change some of our test exceptions for this PR to work correctly. Let us clean it up on our side and if everything looks good I'll push it.

**Comment by tobine** [comment]
This is now clean on our farm. Will wait until tomorrow to merge in case anyone else had input or feedback.

**Comment by mark-lunarg** [comment]
Pushed to Master.  Thanks @tobine.

**Pull request closed without merging**
