### PR TITLE
tests:Fix DynViewportAndScissorMismatch crash

### PR DESCRIPTION
**Pull request by tobine**
This test was crashing on Nvidia drivers.
The crash seems to be a driver bug as the workaround is to not destroy
a descriptor set layout prior to creating gfx pipelines whose
pipeline_layout object was created from the given descriptor set layout

@krOoze note workaround for NV crash

### CODE REVIEW

**Comment by krOoze** [comment]
@tobine is the `VkDescriptorSetLayout` necessary at all?

**Comment by krOoze** [comment]
@tobine The same code is in `PSOViewportStateMultiViewportTests` and `PSOViewportStateTests`. Those do not crash?

**Comment by tobine** [comment]
@krOoze both of the tests you referenced expect errors when attempting to create gfx pipeline so they don't call down to the driver.

**Comment by krOoze** [comment]
@tobine  Oh!

**Pull request merged**
