### PR TITLE
Fix vkUpdateDescriptorsSets typo

### PR DESCRIPTION
**Pull request by marvelous**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Also, @marvelous please amend your commit message to read "layers: Fix vkUpdateDescriptorsSets typo".

**Comment by marvelous** [comment]
I'm sorry, but I won't go to the trouble of signing the CLA until I contribute something covered by copyright. This trivial change is not copyrightable.

**Comment by mark-lunarg** [comment]
@marvelous, getting a pass on the CLA is something to take up with Khronos, it's not up to any of us working on the repo.  You can sign and we can pull in your change, or close the PR and the typo will probably get taken care of in the next maintenance sweep, but thanks for noticing and especially thanks for the PR.

**Comment by marvelous** [comment]
Ok, too bad that Khronos's process does not take this situation into account. Thank you for your help.

**Pull request closed without merging**
