### PR TITLE
CMAKE_INSTALL_PREFIX default is /usr/local on unix

### PR DESCRIPTION
**Pull request by davidhubbard**
In order to build with a custom CMAKE_INSTALL_PREFIX, the line set (CMAKE_INSTALL_PREFIX "") must be removed.

CMake "set" will overwrite anything specified on the command line with cmake -DCMAKE_INSTALL_PREFIX.

### CODE REVIEW

**Comment by davidhubbard** [comment]
Hey Mark, I'm a Mac OS and Linux user, so this pull request probably needs to be checked on a Windows machine.

Also, I just located a boolean, [CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT](http://cmake.3232098.n2.nabble.com/Documentation-for-CMAKE-INSTALL-PREFIX-INITIALIZED-TO-DEFAULT-missing-td6096818.html) that might be useful here. It's an "internal CMake variable," but appears to be fairly widely used.

**Comment by MarkY-LunarG** [comment]
This looks good.  BTW, what's your GitHub account.  Since you've created this issue with your non-GitHub account, it's showing the CLA as unsigned.  And I believe you signed the CLA with your GItHub account.

**Comment by davidhubbard** [comment]
My github account is https://github.com/davidhubbard.

**Comment by MarkY-LunarG** [comment]
Weird, because it's still showing up as not signed.  On the next submission, can you just sign the CLA again if it asks.  For now, I've committed this : bb8de5790dcfd9c76bca8737e00f0aab8cdb719a

**Comment by davidhubbard** [comment]
Will do. I think I've figured out how I'm confusing the CLA assistant on these and I shouldn't have any troubles going forward.

**Pull request closed without merging**
