### PR TITLE
Fix loader bad behavior scribbling through ptr to const caller memory

### PR DESCRIPTION
**Pull request by chrisforbes**
See commit messages for detailed explanation

### CODE REVIEW

**Comment by courtney-g** [comment]
Why is a commit with "DO NOT MERGE: demos: linux demo for loader" on here?

**Comment by jon-lunarg** [comment]
Chris:

This all looks good to me for the loader patch except for one thing.  The patch  always puts the expanded layer names at the beginning of the list.  This is bad since it doesn't preserve the order of layers from the app.  For example in your test program do:
auto names = alloc_protectable<char const *>();
    names[0] = "VK_LAYER_LUNARG_basic";
    names[1] = "VK_LAYER_LUNARG_standard_validation";
    names[2] = "VK_LAYER_LUNARG_generic";

Instead of having the expanded order (closest to the app first) be basic, 8 validation layers, generic. Your patch makes the order basic, generic, 8 validation layers

I think with a some minor modifications your patch could be altered to preserve the order during expansion.

**Comment by chrisforbes** [comment]
@jon-lunarg I agree that would be a better thing to do -- I just did what loader_expand_layer_names was specified to do in its description, placing all the expanded names at the end of the list.

@courtney-g The other commit is a toy demo program. I don't consider it production quality- if it were to be merged, it should be a test case somewhere, and should be adapted to work on all platforms.

**Comment by chrisforbes** [comment]
@jon-lunarg Added one more commit which preserves order during expansion.

**Comment by jon-lunarg** [comment]
Thanks Chris for the patches!

Cherry-picked to master branch.

**Pull request closed without merging**
