### PR TITLE
WIP: Fix find layout to search on each aspect bit.

### PR DESCRIPTION
**Pull request by lentinem**

### CODE REVIEW

**Comment by Tony-LunarG** [comment]
Looks good to me - fixes the sample issue and still catches problems in CTS

**Comment by Tony-LunarG** [comment]
Do you think this is good to go?  We're about to freeze/branch for another SDK release, and having this issue fixed would be desirable.

**Comment by lentinem** [comment]
It's marked WIP because I haven't had a chance to do any testing but if you have tested it it should be fine. Might be too late now though. Sorry I didn't see this Friday.

**Comment by Tony-LunarG** [comment]
Ok - I committed it to master. Thanks!

**Pull request closed without merging**
