### PR TITLE
tests: Fix compressed image copy test

### PR DESCRIPTION
**Pull request by mark-lunarg**
Needed additional format feature checks for the selected formats.  @tobine, can you make sure this takes care of the AMD platform issues?

### CODE REVIEW

**Comment by tobine** [comment]
Still see assert failure on Windows AMD Vega:

> [ RUN      ] VkPositiveLayerTest.UncompressedToCompressedImageCopy
> S:\windows-slave\dev_windows\build\tests\vktestbinding.cpp(504): error: Failed
> Assertion: `vkCreateImage(dev.handle(), &info, 0, &handle) == VK_SUCCESS'
> S:\windows-slave\dev_windows\build\tests\layer_validation_tests.cpp(20366): error: Value of: comp_color_image.initialized()
>   Actual: false
> Expected: true
> [  FAILED  ] VkPositiveLayerTest.UncompressedToCompressedImageCopy (434 ms)

**Comment by mark-lunarg** [comment]
@tobine, @cnorthrop, can one of y'all send me a vulkaninfo from this particular system?  The GPU database says that an AMD Vega does NOT support either transfer_src or transfer_dest format features, so seems like it should be skipping this test.  Our AMDs all support these features and work fine...

**Comment by tobine** [comment]
vulkaninfo attached
[AMD_Vega_vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1411331/AMD_Vega_vulkaninfo.txt)

**Comment by mark-lunarg** [comment]
According to vulkaninfo, both of these formats and both of the features are supported -- no idea why this card is balking.  Added a check for success on image initialization instead of the asserts.

**Pull request merged**
