### PR TITLE
demos: GH692 Added a supporting of wayland wsi

### PR DESCRIPTION
**Pull request by elongbug**
Added a supporting of wayland wsi to cube, tri and smoke.

Signed-off-by: Mun Gwan-gyeong <elongbug@gmail.com>

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Dustin, can you check out the CMake parts, and Tony, can you run through the demo stuff?

**Comment by elongbug** [comment]
Dear dustin, I have tested it with  weston ( reference  wayland compositor) and latest mesa driver on latest arch linux.

**Comment by dustin-lunarg** [comment]
+1 Looks good to me

**Comment by Tony-LunarG** [comment]
Look good to me too

**Comment by dustin-lunarg** [comment]
I cherry picked this to my local master and pushed to GitHub.

**Pull request closed without merging**
