### PR TITLE
WIP: Update event tracking

### PR DESCRIPTION
**Pull request by lentinem**
Account for sequential cross command buffer and cross queue tracking.

### CODE REVIEW

**Comment by tobine** [comment]
Note that I'm seeing seg faults attempting to test this CL. The line I'm faulting on for cube --validate is in vkQueueSubmit:

    for (auto &function : pCB->eventUpdates) {

**Comment by lentinem** [comment]
Thats odd; should be fixed now though.

**Comment by tobine** [comment]
Thanks, Michael. It's working now. I still need to go through the code a bit more but will merge if I don't see any issues.

**Comment by lentinem** [comment]
Thanks. If you can take a look at not just functionality but the design. As I mentioned there are a number of other state tracking fixes that need to happen and would use the same basic design as this but I would like to get feedback on if others would be comfortable using this framework for those types of tasks going forward.

**Comment by stroyan** [comment]
sourceStageMask should be logged as 0x%x instead of %d format.

**Comment by lentinem** [comment]
Done

**Comment by tobine** [comment]
With a bit of reading and re-reading I think I like this approach. Cherry-picked, updated resetCB to clear eventUpdates and pushed to master.

**Pull request closed without merging**
