### PR TITLE
Fix line endings in update_external_resources shell script

### PR DESCRIPTION
**Pull request by mark-lunarg**
Used tr -d to remove line endings for external_revisions files in update_external_sources.sh script.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Fixed the comment.

**Comment by mark-lunarg** [comment]
@jeffbolznv, Github is saying the CLA status is still showing as pending, so maybe it's waiting for you?

**Comment by mark-lunarg** [comment]
@jeffbolznv, ping!

**Comment by jeffbolznv** [comment]
Sorry, I didn't realize I had an action here. I've signed the CLA.

**Comment by mark-lunarg** [comment]
Thanks @jeffbolznv!

**Pull request merged**
