### PR TITLE
Make the loader compatible with Universal Windows drivers

### PR DESCRIPTION
**Pull request by scyganINTEL**
This set of changes makes loader compatible with requirements for "Universal Windows drivers", 
as described in https://msdn.microsoft.com/en-us/library/windows/desktop/mt654039(v=vs.85).aspx

These changes may be needed, if the loader is bundled in unversal driver package.

The changes remove or replace the usage of some of Windows APIs removed from UWD. Linkage with univeral 'umbrella' library is enabled by CMake option:
```
 -DENABLE_WIN10_ONECORE=1
```

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@lenny-lunarg, @scyganINTEL, CI has flagged a failure, the source was not clang-formatted.  The commit messages also need to be changed to match the repo, i.e., loader: blah blah, 50 chars, etc, see the CONTRIBUTING doc.

**Comment by scyganINTEL** [comment]
I believe CI failures are resolved now? :)

**Comment by lenny-lunarg** [comment]
I just pushed these changes to master. I tweaked the commit messages slightly to better adhere to our standards. All I did was change the "loader for UWD" part of each commit message to "loader". This PR is on master in commits fa472852a07e8497f5e4cb7a766bb927967e6e77, 43b42e1ea08a3615510707f94942cbf1efac1957, and 18a1951f0c187d4fb99a05c25fa4bf36100aea58.

Thanks for the contribution!

**Comment by mark-lunarg** [comment]
Thank you very much @lenny-lunarg.

**Pull request closed without merging**
