### PR TITLE
Fix  wayland build problems.

### PR DESCRIPTION
**Pull request by elongbug**
This series solves  Wayland Build Problems. This patches depend on Fix wayland support #10 ( https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/10 ).
( #10 does not cover wayland build fails, this commits fixes that.)

### CODE REVIEW

**Comment by elongbug** [comment]
I've made new commits that address   @jackoalan, @Antidote 's comments.

**Comment by mark-lunarg** [comment]
I've rebased these onto master, fixed the Windows build, and made a corresponding set of changes for the VulkanTools repo.  We are reorganizing things at the moment so hopefully these changes should be pushed and available sometime tomorrow or Thursday at the latest.

**Comment by elongbug** [comment]
@mark-lunarg , do I have to change something on this commits? (so then, please guide me ^^) or should I wait another dependent commit?

**Comment by mark-lunarg** [comment]
I've taken care of the required changes.  Our repository has changed structure somewhat and the changes also needed to be propagated to the LunarG/VulkanTools repo.  The changes are being testing and should be pushed soon.  Sorry for the delay.

**Comment by elongbug** [comment]
@mark-lunarg , NP If you need any modification on my commit, I'll fix it asap.

**Comment by mark-lunarg** [comment]
One thing that will help -- in layers/CMakeLists.txt there is a section that sets an environment variable 'VULKAN_WSI' to the current Linux WSI type, but this environment variable does not appear to be used -- are there any objections to removing this code section?

**Comment by elongbug** [comment]
@mark-lunarg  , I removed " VULKAN_WSI env settings" from  layers/CMakeLists.txt.

**Comment by mark-lunarg** [comment]
OK, this is now in Master along with the associated changes.  Please give it a run-through and let us know if additional changes/fixes are needed.  Thanks!

**Pull request closed without merging**
