### PR TITLE
CreatePipelineLayout device limits VUs (re-submit PR2255)

### PR DESCRIPTION
**Pull request by daveh-lunarg**
Reverted commits from PR #2255 (rolled back while sorting out a test failure on AMD Vega).

> Adds 6 valid usage checks of device physical limits to VkCreatePipelineLayouts(). Re-organizes the validation code into PreCallValidation, dispatch, and PostCallRecord functions. Adds 2 tests to provoke the VUs.

### CODE REVIEW

**Comment by daveh-lunarg** [comment]
@tobine can you triage the failure on Vega?  We don't have one on hand.

**Comment by tobine** [comment]
Yep, checking this out now.

**Comment by daveh-lunarg** [comment]
@tobine:  I'm able to repro it on an AMD R9 Windows system, so not Vega-specific.  I'll check it out.  Thanks!

**Comment by tobine** [comment]
They're maxing out limits at 4294967295 (2^32-1), meaning they can handle as many descriptors as you can throw at them.
Should special-case this and skip test.

**Comment by mark-lunarg** [comment]
... or use devlimits to artificially reduce the number?

**Comment by daveh-lunarg** [comment]
Added MAX_INT limits guard to skip the test.

**Pull request merged**
