### PR TITLE
Remove now-deprecated device limits layer

### PR DESCRIPTION
**Pull request by mark-lunarg**

### CODE REVIEW

**Comment by tobine** [comment]
1000+ lines gone. My kinda change. Clean on our farm.
LGTM :+1:

**Comment by mark-lunarg** [comment]
Pushed to Master.

**Comment by renelindsay** [comment]
Just out of curiosity... device limits layer sounds kind of important.
Has its functionality been moved to another layer?

**Comment by tobine** [comment]
Yes @renelindsay @mark-lunarg rolled the checks into core validation

**Pull request closed without merging**
