### PR TITLE
demos: On Android, treat 1st-time new window different from nth-time.

### PR DESCRIPTION
**Pull request by ianelliottus**
This fixes an issue if cube ever got a new window, it would leak objects and grow large.

### CODE REVIEW

**Comment by courtney-g** [comment]
+1

**Comment by mark-lunarg** [comment]
Hey Ian, commit looks good, but please take a look at the commit message guidelines from the [Vulkan Layer Implementation Guidelines and Features](https://docs.google.com/a/lunarg.com/document/d/1AygM25GmZgA8sFxPHUhOMHVkbdS_dyt9mW4UXskGLs4/edit?usp=sharing).  Thanks!

**Comment by ianelliottus** [comment]
Hi @mark-lunarg.  That's a big document:-).  I'll change the commit ID before pushing.  BTW, there's a reference to "the Gerrit Automated Build system".  Is that something that you have at LunarG?

**Comment by ianelliottus** [comment]
Cherry-picked and pushed to master

**Comment by mark-lunarg** [comment]
Yes, it's something that Dustin put together for pre-checking validation and code reviews.  If we can ever catch our breath, the idea is to move it beyond our firewall and share it with you guys.

**Pull request closed without merging**
