### PR TITLE
Move python scripts into subdirectory

### PR DESCRIPTION
**Pull request by mark-lunarg**
Move the codegen and utility python scripts and vk.xml into a scripts dir.  

Also, vk-layer-introspect.py is removed in this patch series -- if anyone speaks up I'll happily keep it.

@ardaLunarG , I'll work on a VT companion series before this lands in LVL.

### CODE REVIEW

**Comment by tobine** [comment]
👎 Just want to make sure this is held up until we can run it through our farm which I don't suspect will be until Mon as we can't currently access it remotely. Will give it a try then and thumb up if clean.

**Comment by mark-lunarg** [comment]
@tobine, bump.

**Comment by tobine** [comment]
Verified clean on our farm. :+1:

**Comment by mark-lunarg** [comment]
Pushed to Master.  Thanks @tobine.

**Pull request closed without merging**
