### PR TITLE
WIP: Add checking for may alias bit.

### PR DESCRIPTION
**Pull request by lentinem**
Not sure how to make this only diff against the prior pull request.

### CODE REVIEW

**Comment by lentinem** [comment]
Rebased: Note there are some formatting changes that somehow didn't get merged from the change this depended on. I would be in favor of doing them anyway.

**Comment by tobine** [comment]
I think that format was updated due to modified clang-format for layers with larger line length. I'd like to just skip the format CL and only pull the alias check changes from second CL.

**Comment by tobine** [comment]
On second thought, alias commit doesn't cherry pick cleanly without the format changes so I'll just take them both. Having the shortly line length isn't an issue.

**Comment by lentinem** [comment]
I just pushed the new line length

**Comment by tobine** [comment]
Thanks. Validated and pushed to master.

**Pull request closed without merging**
