### PR TITLE
Remove unused options/code from vk_helper.py

### PR DESCRIPTION
**Pull request by mark-lunarg**

### CODE REVIEW

**Comment by jeremy-lunarg** [comment]
+1 lgtm

**Comment by tobine** [comment]
I don't use or care about the graphviz or noaddr stuff anymore and I have no recollection of other stuff being axed so I'm fine with all of this.
LGTM :+1:

**Comment by mark-lunarg** [comment]
Pushed to Master.

**Comment by stroyan** [comment]
I see VulkanTools still using get_struct_chain_size from its version of vk_helper.py.
Removing it from upstream may lead to additional git merge conflicts taking vk_helper.py in the future.

**Comment by stroyan** [comment]
Ah.  I see that I mistook a big block of change in indentation for a deletion.  Nevermind.

**Pull request closed without merging**
