### PR TITLE
demos: Change logo absolute path to relative path

### LINKED ISSUE #2424: vulkaninfo: For HTML output, there is an image ref to a local filesystem.
```c
fprintf(out, "\t\t\t<img src='C:/Git/VulkanTools/layersvt/images/lunarg.png' />\n");
```

### PR DESCRIPTION
**Pull request by shannon-lunarg**
Fixes #2424

### CODE REVIEW

**Comment by mark-lunarg** [comment]
VIA has a couple of examples of this, but I'd agree with Karl and just remove it, at least for now.

**Comment by shannon-lunarg** [comment]
@karl-lunarg My thought process was that if the user put both repos in the recommended places (some overarching development directory) the logo would appear and if the configuration varied or if  VulkanTools didn't exist on the system the logo simply wouldn't show up. This is the case for Chrome but now that I've switched to viewing this on Firefox, I can see the problem..

I'd prefer a permanent URL to the logo (it looks nicer) but I can just remove the line for now.

Note: This line was copied and pasted from the api dump html template which suffers from the same erroneous absolute file path.

**Comment by karl-lunarg** [comment]
Yes, but many users are going to be using vulkaninfo out of an SDK where there are no GitHub repos checked out.   In addition, it is possible that a user might run vulkaninfo to generate an HTML file and then send it via email to someone to look at.  The recipient isn't likely to have the repos and isn't likely to download the attachment into the exact location in the repo that would make this relative path work.

I think that removing the reference is the best solution.  If we decide to host the image file on a server someplace, then we could put it back.  But I don't think it is worth it.

I'll open an issue on VulkanTools to address the problem there.

Thanks for fixing this!

**Comment by shannon-lunarg** [comment]
@karl-lunarg You make a lot of great points. Thanks for all the info!

**Comment by shannon-lunarg** [comment]
Pushed to master

**Pull request closed without merging**
