### PR TITLE
validation: Add a warning for LOAD_OP_LOAD + LAYOUT_UNDEFINED

### PR DESCRIPTION
**Pull request by jekstrand**
While not technically an error (VK_IMAGE_LAYOUT_UNDEFINED is always
allowed as an initial layout), this combination is almost never what
you actually want.  If nothing else, it's a potential performance
problem because VK_ATTACHMENT_LOAD_OP_LOAD is liable to be more
expensive than VK_ATTACHMENT_LOAD_OP_DONT_CARE.  Give developers a
helpful warning in this case.

This would have caught an actual bug in some of the Sascha Willems
demos as fixed in this PR:

https://github.com/SaschaWillems/Vulkan/pull/400

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@karl-lunarg, validation or assistant layer?

**Comment by karl-lunarg** [comment]
This is a good example of something that goes in the assistant layer.

But since the code has already been (nicely) written, I'd suggest accepting this PR and adding this item to the assistant layer list along with a note that the same check is in this PR.  When the assistant layer goes out with this check, we can then think about taking this out of the VLs.  I'd rather risk a little redundancy than miss this useful check.

**Comment by mark-lunarg** [comment]
Excellent.  @jekstrand, if you click through the CLA we'll get this in.

**Comment by jekstrand** [comment]
There you go.  CLA signed.

**Comment by mark-lunarg** [comment]
Thanks a bunch @jekstrand -- normalized commit message and pushed to Master.

**Pull request closed without merging**
